# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  log-level:
    description: |
      Configures the log level of gunicorn. 

      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. Will default to the name of the deployed
        application.
    default: ""
    type: string
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: "temporal-tls"
    type: string
  port:
    description: |
        The port used by the Temporal Web UI Server and the HTTP API.
    default: 8080
    type: int
  default-namespace:
    description: |
        The default Temporal namespace that the Web UI opens first.
    default: "default"
    type: string
  auth-enabled:
    description: |
        Whether or not OIDC authentication is enabled.
    default: False
    type: boolean
  auth-provider-url:
    description: |
        The .well-known IDP discovery URL for authentication and authorization.
    default: ""
    type: string
  auth-client-id:
    description: |
        The client ID used for authentication or authorization.
    default: ""
    type: string
  auth-client-secret:
    description: |
        The client secret used for authentication and authorization.
    default: ""
    type: string
  auth-scopes:
    description: |
        The comma-separated array of resources required to be accessed from the access token.
    default: "[openid,profile,email]"
    type: string
