name: Integration tests

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    uses: arjun11-malik/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      provider: k8s
      use-canonical-k8s: true
      channel: edge
      juju-channel: 3.6/stable
      charmcraft-channel: latest/edge
      modules: '["test_charm.py", "test_refresh.py", "test_traefik_ingress.py"]'
      pre-run-script: .github/scripts/init-pytest-ui.sh
      tmate-debug: true
      tmate-timeout: 60

