name: Integration tests

on:
  pull_request:
  workflow_call:

jobs:
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-environments:
          - integration
          - integration-traefik
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.6/stable
          provider: microk8s
          microk8s-addons: "ingress storage dns rbac registry metallb:10.15.119.2-10.15.119.4"
          channel: 1.25-strict/stable
      - name: Run integration tests
        run: tox -e ${{ matrix.tox-environments }} -- --model testing
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: temporal-ui-k8s
          model: testing
