name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
      - main
      - track/**

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@8892eb826818585b397295e40276ddd0c5d3d459
    secrets: inherit
    with:
      integration-test-provider: microk8s
      integration-test-microk8s-addons: "ingress storage dns rbac registry"
      integration-test-provider-channel: 1.25-strict/stable
      integration-test-juju-channel: 3.1/stable
